version: '3'
services:
  thingslogic-scd:
    build: ./
    container_name: thingslogic-scd
    volumes:
      - ./crate/data:/var/lib/crate
      - ./crate/config:/etc/crate
      - ./grafana/data:/var/lib/grafana/config
      - ./grafana/config:/etc/grafana
      - ./nodered/data:/root/.node-red
    ports:
      - "1880:1880"
      - "3000:3000"
      - "4200:4200"
      - "4300:4300"
      - "5432-5532:5432-5532"
    tty: true
