# Crate Configuration

network.host: _site_
cluster.name: thingslogic
node.name: thingslogic
bootstrap.memory_lock: false

# Paths
path:
  logs: /data/log
  data: /data/data
blobs:
  path: /data/blobs
